services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - mailpit
    command: >
      sh -c "sleep 10 &&
      python manage.py migrate &&
      python create_superuser.py &&
      python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped  

  db:
    image: postgres:16
    container_name: postgres_db
    #ports:
    #  - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    volumes:
      - ./data:/data
    ports:
      - "8025:8025" 
      - "1025:1025" 
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    restart: unless-stopped

volumes:
  postgres_data: