# Generated by Django 6.0.2 on 2026-02-25 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas_dirigidas', related_query_name='dm_campana', to=settings.AUTH_USER_MODEL)),
                ('jugadores', models.ManyToManyField(blank=True, related_name='campanas_participadas', related_query_name='jugador_campana', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('vida', models.PositiveIntegerField(default=50)),
                ('dificultad', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(default='Monstruo', max_length=50)),
                ('nota_narrativa', models.TextField(blank=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemigos', related_query_name='enemigo_campana', to='game.campana')),
            ],
            options={
                'unique_together': {('nombre', 'campana')},
            },
        ),
        migrations.CreateModel(
            name='PerfilJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, max_length=500)),
                ('preferencias_dados', models.CharField(blank=True, help_text="Ej: 'prefiero d20'", max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_jugador', related_query_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('vida_maxima', models.PositiveIntegerField(default=100)),
                ('vida_actual', models.PositiveIntegerField(default=100)),
                ('clase', models.CharField(default='Guerrero', max_length=50)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes_campana', related_query_name='personaje_campana', to='game.campana')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nombre', 'campana')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('ataque', 'Ataque'), ('curacion', 'Curación'), ('otros', 'Otros')], max_length=20)),
                ('tipo_dado', models.CharField(choices=[('d20', 'D20'), ('d6', 'D6'), ('d8', 'D8'), ('d10', 'D10'), ('d12', 'D12')], max_length=10)),
                ('resultado_dado', models.PositiveIntegerField()),
                ('modificador', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('exito', models.BooleanField()),
                ('dano_curacion', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acciones', to='game.campana')),
                ('enemigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_enemigo', to='game.enemigo')),
                ('personaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_personaje', to='game.personaje')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
