# Generated by Django 6.0.2 on 2026-03-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='batalla_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campana',
            name='indice_turno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='turno_actual',
            field=models.CharField(default='personajes', max_length=20),
        ),
    ]
