name: Pylint

on:
  pull_request:
    branches:
      - develop  # Cambia según tu rama principal
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker container
        run: docker compose build

      - name: Run Pylint inside Docker
        run: docker compose run --rm lint